/** Public shared UI primitive exports for Rectangle feature modules. */
export {
  Badge,
  Button,
  Card,
  Checkbox,
  ConfirmDialog,
  DataTable,
  Drawer,
  EmptyState,
  ErrorState,
  Field,
  IconButton,
  Input,
  LoadingState,
  Modal,
  PageGrid,
  PageHeader,
  Select,
  SuccessState,
  Switch,
  Textarea,
  Toast,
  Toolbar,
  WarningState,
  type BadgeProps,
  type ButtonProps,
  type CheckboxProps,
  type ConfirmDialogProps,
  type DataTableColumn,
  type DataTableProps,
  type DrawerProps,
  type FieldProps,
  type IconButtonProps,
  type InputProps,
  type ModalProps,
  type PageGridProps,
  type SelectProps,
  type StateBlockProps,
  type SwitchProps,
  type TextareaProps,
  type ToastProps,
} from "./primitives";
